<?php

function media_displays_theme() {
  $theme = array(
    'media_displays_download_file_alt' => array(
      'variables' => array('items' => NULL),
      'file' => 'media_displays.formatter.inc'
    ),
    'media_displays_download_alt_item' => array(
      'variables' => array('file' => NULL),
      'file' => 'media_displays.formatter.inc'
    ),
    'media_displays_image_alt_quotes' => array(
      'variables' => array(
        'items' => NULL,
        'path' => NULL,
        'image_style' => NULL,
      ),
      'file' => 'media_displays.formatter.inc'
    ),
  );
  return $theme;
}

/**
 * Implementation of hook_field_formatter_info().
 */
function media_displays_field_formatter_info() {
  $formatters = array(
    'direct_download_alt' => array(
      'label' => t('Download File (ALT Text)'),
      'field types' => array('file', 'image'),
      'description' => t('Displays a link to direct download the file using the ALT text.')
    ),
    'image_alt_quotes' => array(
      'label' => t('Image (ALT quotes)'),
      'field types' => array('file', 'image'),
      'description' => t('Allows alt attributes to have single quotes'),
      'settings' => array(
        'media_displays_image_style' => '',
        'media_displays_image_link' => '',
      ),
    ),
  );
  return $formatters;
}

/**
 * Implements hook_field_formatter_settings_form().
 */
function media_displays_field_formatter_settings_form($field, $instance, $view_mode, $form, &$form_state) {
  $display = $instance['display'][$view_mode];
  $settings = $display['settings'];
  $image_styles = image_style_options(FALSE, PASS_THROUGH);

  $element['media_displays_image_style'] = array(
    '#title' => t('Image style'),
    '#type' => 'select',
    '#default_value' => $settings['media_displays_image_style'],
    '#empty_option' => t('None (original image)'),
    '#options' => $image_styles,
  );

  $link_types = array(
    'content' => t('Content'),
    'file' => t('File'),
  );
  $element['media_displays_image_link'] = array(
    '#title' => t('Link image to'),
    '#type' => 'select',
    '#default_value' => $settings['media_displays_image_link'],
    '#empty_option' => t('Nothing'),
    '#options' => $link_types,
  );

  return $element;
}

/**
 * Implementation of hook_field_formatter_view().
 */
function media_displays_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();

  switch ($display['type']) {
    case 'direct_download_alt':
      $element[0] = array(
        '#theme' => 'media_displays_download_file_alt',
        '#items' => $items
      );
      break;
    case 'image_alt_quotes':
      if ($display['settings']['media_displays_image_link'] == 'content') {
        $uri = entity_uri($entity_type, $entity);
      }
      elseif ($display['settings']['media_displays_image_link'] == 'file') {
        $link_file = TRUE;
      }

      foreach ($items as $delta => $item) {
        if (isset($link_file)) {
          $uri = array(
            'path' => file_create_url($item['uri']),
            'options' => array(),
          );
        }
        $element[$delta] = array(
          '#theme' => 'media_displays_image_alt_quotes',
          '#items' => $items,
          '#image_style' => $display['settings']['media_displays_image_style'],
          '#path' => isset($uri) ? $uri : '',
        );
      }
      break;
  }
  return $element;
}

/**
 *  Implements hook_form_FORM_ID_alter().
 */
function media_displays_form_media_wysiwyg_format_form_alter(&$form, &$form_state, $form_id) {
//  dpm($form);
//  dpm($form_state);
}

/**
 *  Implements hook_filter_info_alter().
 */
function media_displays_filter_info_alter(&$info) {
  $info['media_filter']['process callback'] = '_media_displays_filter';

//  media_wysiwyg_format_form()
}

function _media_displays_filter($text) {
  $offset = 0;
  while (strpos($text, '[[', $offset) > 0) {
    $start = strpos($text, '[[', $offset) + 2;
    $end = strpos($text, ']]', $start) - strpos($text, '[[', $offset) - 2;

    $token = substr($text, $start, $end);
    $json = json_decode($token, TRUE);

    if (isset($json['direct_download']) && $json['direct_download']) {
      $file = file_load($json['fid']);
      $url = file_create_url($file->uri);
      $text = str_replace('[[' . $token . ']]', l($json['fields']['link_text'], $url), $text);
    }
    else {
      $offset = strpos($text, '[[', $offset) + 2;
    }
  }
  $text = media_wysiwyg_filter($text);
  return $text;
}


function media_displays_init() {
  drupal_add_css('.view-media-default iframe {width:200px; height:140px;}', 'inline');
}
